exercise/exercise/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('practice/', include('practice.urls')),
    path('', RedirectView.as_view(url='/practice/'), name='index'),
]

exercise/practice/urls.py
from django.urls import path
from .views import index, add_detail, edit_detail, delete_detail


app_name = 'practice'
urlpatterns = [
    path('', index, name='index'),
    path('add_detail/', add_detail, name='add_detail'),
    path('edit_detail/<int:id>/', edit_detail, name='edit_detail'),
    path('delete_detail/<int:id>/', delete_detail, name='delete_detail'),
]

exercise/practice/models.py
from django.db import models

# Create your models here.


class Person(models.Model):
    name = models.CharField(max_length=200)
    age = models.IntegerField()
    phone_number = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)

exercise/practice/forms.py
from django import forms
from .models import Person


class AddNewPerson(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['name', 'age', 'phone_number', 'email']

exercise/practice/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from .models import Person
from .forms import AddNewPerson


def index(request):
    persons = Person.objects.all()
    context = {
        'objects': persons,
    }
    return render(request, 'practice/index.html', context)


def add_detail(request):
    if request.method == 'POST':
        form = AddNewPerson(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/practice')
        context = {
            'form': form,
        }
        return render(request, 'practice/add_detail.html', context)

    else:
        form = AddNewPerson()
        context = {
            'form': form
        }
        return render(request, 'practice/add_detail.html', context)


def edit_detail(request, id):
    instance = get_object_or_404(klass=Person, pk=id)
    if request.method == 'POST':
        form = AddNewPerson(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('/practice')
        context = {
            'form': form,
        }
        return render(request, 'practice/edit_detail.html', context)

    # """
    # line 46-48
    # form = AddNewPerson(request.POST)
    # if form.is_valid():
    #     name = form.cleaned_data['name']
    #     age = form.cleaned_data['age']
    #     phone_number = form.cleaned_data['phone_number']
    #     email = form.cleaned_data['email']
    # """

    else:
        form = AddNewPerson(instance=instance)
        context = {
            'form': form
        }
        return render(request, 'practice/edit_detail.html', context)


def delete_detail(request, id):
    if request.method == 'POST':
        try:
            person = Person.objects.get(id=id)
        except Person.DoesNotExist:
            raise Http404('Page do not exist')
        person.delete()
        return redirect('/practice')
        context = {
            'person': person
        }
        return render(request, 'practice/delete_detail.html', context)
    else:
        return render(request, 'practice/delete_detail.html')

exercise/practice/templates/practice/add_detail.html
{% extends 'practice/base.html' %}
{% block title %}<title>Add</title>{% endblock %}
{% block content %}
<div class='container'>
  <h1 class='text-center' style="font-size: 60px;">Add New People</h1>
  <p class='lead text-center font-italic'>
    add your new people
  </p>
  <h2>
    <div class='row justify-content-center' style='font-size: 20px;'>
      <form method="post">
        {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-primary" type="submit">Submit</button>
      </form>
    </div>
  </h2>
</div>
{% endblock %}

exercise/practice/templates/practice/base.html
<!doctype html>
<html>
    {% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block title %}{% endblock %}
</head>

<body class="p-3 bg-light">
    {% block content %}
    {% endblock %}

    {% block baseJS %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
    {% endblock %}
</body>

</html>

exercise/practice/templates/practice/delete_detail.html
{% extends 'practice/base.html' %}
{% block title %}<title>Delete</title>{% endblock %}
{% block content %}
<div class='container'>
  <h1 class='text-center' style="font-size: 60px;">Delete Profile</h1>
  <p class='lead text-center font-italic'>
    delete this profile
  </p>
  <form class='text-center' method="post">
    {% csrf_token %}
    <button class="btn btn-primary " type="submit">CONFIRM</button>
  </form>
</div>
{% endblock %}

exercise/practice/templates/practice/edit_detail.html
{% extends 'practice/base.html' %}
{% block title %}<title>Edit</title>{% endblock %}
{% block content %}
<div class='container'>
  <h1 class='text-center' style="font-size: 60px;">Edit Profile</h1>
  <p class='lead text-center font-italic'>
    change the profile
  </p>
  <h2>
    <div class='row justify-content-center' style='font-size: 20px;'>
      <form method="post">
        {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-primary" type="submit">Submit</button>
      </form>
    </div>
  </h2>
</div>
{% endblock %}

exercise/practice/templates/practice/index.html
{% extends 'practice/base.html' %}
{% block title %}<title>PPLz</title>{% endblock %}
{% block content %}
<div class='container'>
  <h1 class='text-center' style="font-size: 60px;">PPLz</h1>
  <p class='lead text-center font-italic'>
    easily manage all your people
  </p>
  <h2>
    <a class='btn btn-outline-primary' href="{% url 'practice:add_detail' %}" style='width: 80px;'>Add</a>
  </h2>
  <h2>
    <table class='table'>
      <thead class='font-weight-bolder' style='font-size: 20px;'>
        <tr>
          <th scope='col'>Name</th>
          <th scope='col'>Age</th>
          <th scope='col'>Phone Number</th>
          <th scope='col'>Email</th>
          <th scope='col'></th>
        </tr>
      </thead>
      <tbody class='font-weight-normal' style='font-size: 20px;'>
        {% for object in objects %}
        <tr>
          <td><a class="text-decoration-none" href="{% url 'practice:edit_detail' id=object.id %}">{{ object.name }}</a>
          </td>
          <td>{{ object.age }}</td>
          <td>{{ object.phone_number }}</td>
          <td>{{ object.email }}</td>
          <td><a class="text-decoration-none" href="{% url 'practice:delete_detail' id=object.id %}">delete</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </h2>
</div>
{% endblock %}